# Generated by Django 5.0.14 on 2026-08-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera_kit_kyc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycverification',
            name='liveness_reason',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='liveness_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
